name: cargo-dist release
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-dist
        run: cargo install cargo-dist --locked
      - name: Build
        run: cargo dist build --no-local-paths
      - uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: dist/**

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-dist
        run: cargo install cargo-dist --locked
      - name: Build (universal2)
        run: cargo dist build --no-local-paths
      - uses: actions/upload-artifact@v4
        with:
          name: macos-artifacts
          path: dist/**

  # OPTIONAL: auto-create a GitHub Release on tags and upload installers
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/*/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: cargo dist plan --print artifacts --no-local-paths -v
