name: dist
on:
  workflow_dispatch:
  push:
    tags: ["v*"]

permissions:
  contents: write   # needed if you run a release upload later

jobs:
  build:
    name: build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # cargo-dist likes tags/history

      - uses: dtolnay/rust-toolchain@stable

      # Fast install of cargo-dist (prebuilt) on all OSes
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main
      - name: Install cargo-dist
        run: cargo binstall -y cargo-dist@0.30.0

      # Windows: install WiX (MSI toolchain)
      - name: Install WiX
        if: matrix.os == 'windows-latest'
        run: choco install wixtoolset --version=3.14.1 -y

      # (Optional) Show what will be built (nice for debugging)
      - name: Plan
        run: cargo dist plan --print artifacts --no-local-paths -v

      - name: Build installers
        run: cargo dist build --no-local-paths -v

      - uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: dist/**

  # Optional: publish to a GitHub Release when you push a tag
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

